### ISSUE TITLE
SAFE AREA ERROR

### ISSUE THREAD

**Issue by ghost** [giovannidavi/react-native-animated-screen#2]
TypeError: Cannot read property 'initialWindowSafeAreaInsets' of undefined

This error is located at:
    in AnimatedScreenWrapper (at allProdcuts.js:12)

**Comment by giovannidavi** [comment]
The issue was caused by a deprecation in one of the package dependencies. 
Resolved by [v1.1.1](https://github.com/giovannidavi/react-native-animated-screen/pull/4)
